### ISSUE TITLE
UUID Error avec AzAuth

### ISSUE THREAD

**Issue by Tealwen** [Azuriom/Azuriom#151]
Bonjour,

j'ai "trouvé" un petit problème je suis sous azuriom 1.0.2 et voici a quoi ressemble mon uuid a moi : a078f653-a947-45e1-8f93-83287c5663c0 et l'uuid des autre personne ressemble a ceci ; 55351e8b66133f278f84874e6412558e ce qui fait que azauth me dit que les uuids ne sont pas valide et ne connecte pas , pour "verifié" entre guillemet , j'ai modifier un uuid d'un compte qui ne fonctionnait pas dans la bdd pour le formaté correctement et depuis cela fonctionne je ne sais pas si c'est un problème de Azuriom ou de AzAuth mais je fait remonté

**Comment by MrMicky-FR** [comment]
Bonjour, normalement cette version devrait corriger le problème : https://azuriom.s3.fr-par.scw.cloud/azauth-1.0-SNAPSHOT.jar
Si c'est bon je pourrais commit :)

**Comment by Tealwen** [comment]
Salut ,

déjà merci de ta réponse rapide , et je désoler mais cela ne règle pas le problème, je suis pas sur que le probleme vienne de AzAuth mais plutot de la facon dont le site format les uuid comme je te les envoyer les uuid des autres utilisateurs sont tous colé et non pas les tiret ect pour ressemblé a un vraie uuid du moin un valide car quand je modifie a la main les uuid non valide en y ajoutent les tirets bah ce la foncitonne parfaitement je te donne au cas ou l'erreur que cela me mais 

`Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Invalid UUID string: 569e63bb02f33326b440bc8e2376f03c
	at java.util.UUID.fromString(UUID.java:194)
	at com.google.gson.internal.bind.TypeAdapters$24.read(TypeAdapters.java:550)
	at com.google.gson.internal.bind.TypeAdapters$24.read(TypeAdapters.java:543)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:870)
	at com.azuriom.azauth.AzAuthenticator.post(AzAuthenticator.java:173)
	at com.azuriom.azauth.AzAuthenticator.authenticate(AzAuthenticator.java:94)
	at com.azuriom.azauth.AzAuthenticator.authenticate(AzAuthenticator.java:73)
	at fr.droopi.launcher.LauncherPanel$3.handle(LauncherPanel.java:207)
	at fr.droopi.launcher.LauncherPanel$3.handle(LauncherPanel.java:201)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$358(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by MrMicky-FR** [comment]
Je viens de vérifier  j'avais upload le mauvais .jar, ça devrait être bon maintenant en téléchargant à nouveau.

Concernant le problème, les UUID undashed (sans tirets) sont aussi valides, et donc cette version de AzAuth devrait les prendre en charge correctement (et c'est plus pratique que de modifier l'ensemble des UUID dans la base de données)

**Comment by Tealwen** [comment]
ca fonctionne c'est good merci beaucoup
