### ISSUE TITLE
Discord webhooks are broken

### ISSUE THREAD

**Issue by gru2007** [Azuriom/Azuriom#353]
### Bug description

Discord webhook messages are not being send

### Step to reproduce

Try create a post with webhooks sending enabled, there will be error in logs

### Errors / Logs

```
[2023-07-31 19:21:11] production.ERROR: HTTP request returned status code 400:
{"embeds": ["0"]}
 {"userId":1,"exception":"[object] (Illuminate\\Http\\Client\\RequestException(code: 400): HTTP request returned status code 400:
{\"embeds\": [\"0\"]}
 at /var/www/mine/vendor/laravel/framework/src/Illuminate/Http/Client/Response.php:272)
[stacktrace]
#0 /var/www/mine/vendor/laravel/framework/src/Illuminate/Http/Client/Response.php(289): Illuminate\\Http\\Client\\Response->toException()
#1 /var/www/mine/app/Support/Discord/DiscordWebhook.php(149): Illuminate\\Http\\Client\\Response->throw()
#2 /var/www/mine/app/Http/Controllers/Admin/PostController.php(54): Azuriom\\Support\\Discord\\DiscordWebhook->send()
#3 /var/www/mine/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(756): Azuriom\\Http\\Controllers\\Admin\\PostController->Azuriom\\Http\\Controllers\\Admin\\{closure}()
#4 /var/www/mine/app/Http/Controllers/Admin/PostController.php(54): rescue()
#5 /var/www/mine/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Azuriom\\Http\\Controllers\\Admin\\PostController->store()
#6 /var/www/mine/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#7 /var/www/mine/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/mine/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#9 /var/www/mine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#10 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/mine/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authorize->handle()
#13 /var/www/mine/app/Http/Middleware/EnsureTwoFactorAuthEnabled.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Azuriom\\Http\\Middleware\\EnsureTwoFactorAuthEnabled->handle()
#15 /var/www/mine/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authorize->handle()
#17 /var/www/mine/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#19 /var/www/mine/app/Http/Middleware/LogoutIfSuspended.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Azuriom\\Http\\Middleware\\LogoutIfSuspended->handle()
#21 /var/www/mine/app/Http/Middleware/CheckForMaintenanceSettings.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Azuriom\\Http\\Middleware\\CheckForMaintenanceSettings->handle()
#23 /var/www/mine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#25 /var/www/mine/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#27 /var/www/mine/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#29 /var/www/mine/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#31 /var/www/mine/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/mine/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#33 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#34 /var/www/mine/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#36 /var/www/mine/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#38 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/mine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#40 /var/www/mine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#41 /var/www/mine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#42 /var/www/mine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#43 /var/www/mine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#44 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#45 /var/www/mine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/mine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#47 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#48 /var/www/mine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/mine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#51 /var/www/mine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#53 /var/www/mine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#55 /var/www/mine/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#57 /var/www/mine/plugins/cloudflare/src/Middleware/TrustCloudflare.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Azuriom\\Plugin\\CloudflareSupport\\Middleware\\TrustCloudflare->handle()
#59 /var/www/mine/app/Http/Middleware/EnsureInstalled.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Azuriom\\Http\\Middleware\\EnsureInstalled->handle()
#61 /var/www/mine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/mine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#63 /var/www/mine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#64 /var/www/mine/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#65 {main}
"} 
```

### Web server

Apache

### Database type

MariaDB

### PHP version

8.2

**Comment by MrMicky-FR** [comment]
Which Azuriom version are you using ?

**Comment by gru2007** [comment]
> Which Azuriom version are you using ?

1.0.17

**Comment by MrMicky-FR** [comment]
Can you send a screen recording or exactly how to reproduce the issue (content of post, etc), as when testing with a regular post, the webhook works fine, see this recording:

https://github.com/Azuriom/Azuriom/assets/30863452/e1aad194-630e-44c4-b89c-fcac6c581b0e

**Comment by gru2007** [comment]
Sure, I’ll test it on fresh installed azuriom in near future

**Comment by MrMicky-FR** [comment]
This issue is causes by the SkinAPI plugin, as it uses relatives URLs, which aren’t supported in Discord emebed. Until @Javdu10 update the plugib, you can manually edit the file `plugins/skin-api/src/Providers/SkinApiServiceProvider.php` and replace this line https://github.com/AzuriomCommunity/Plugin-SkinAPI/blob/4609daa4fc2efedfb79dfe99fc505e0fdc2ab224/src/Providers/SkinApiServiceProvider.php#L36, with
```php
return url(Storage::disk('public')->url("face/{$user->id}.png"));
```
