### ISSUE TITLE
Error after buy packages

### ISSUE THREAD

**Issue by LegoCraftNW** [Azuriom/Azuriom#377]
### Bug description

site gives this error when you buy a package "An unexpected error occured during payment, your purchase got refund" 

I am getting this error even though I increased the php timeout values

![image](https://github.com/Azuriom/Azuriom/assets/21240809/249082b0-32a1-4740-9e2a-8fb1cc484faf)

### Step to reproduce

Install script for rust server
give yourself some coins
buy a pack

### Errors / Logs

```
[2023-09-03 17:01:32] production.ERROR: Client read timeout {"userId":1,"exception":"[object] (WebSocket\\TimeoutException(code: 1024): Client read timeout at /var/www/vhosts/hidden.com/httpdocs/vendor/textalk/websocket/lib/Connection.php:464)
[stacktrace]
#0 /var/www/vhosts/hidden.com/httpdocs/vendor/textalk/websocket/lib/Connection.php(166): WebSocket\\Connection->read()
#1 /var/www/vhosts/hidden.com/httpdocs/vendor/textalk/websocket/lib/Connection.php(115): WebSocket\\Connection->pullFrame()
#2 /var/www/vhosts/hidden.com/httpdocs/vendor/textalk/websocket/lib/Client.php(221): WebSocket\\Connection->pullMessage()
#3 /var/www/vhosts/hidden.com/httpdocs/app/Games/Steam/Servers/Protocol/RustRcon.php(38): WebSocket\\Client->receive()
#4 /var/www/vhosts/hidden.com/httpdocs/app/Games/Steam/Servers/RustRcon.php(58): Azuriom\\Games\\Steam\\Servers\\Protocol\\RustRcon->sendCommand()
#5 /var/www/vhosts/hidden.com/httpdocs/plugins/shop/src/Models/Package.php(228): Azuriom\\Games\\Steam\\Servers\\RustRcon->sendCommands()
#6 /var/www/vhosts/hidden.com/httpdocs/plugins/shop/src/Models/PaymentItem.php(66): Azuriom\\Plugin\\Shop\\Models\\Package->deliver()
#7 /var/www/vhosts/hidden.com/httpdocs/plugins/shop/src/Models/Payment.php(124): Azuriom\\Plugin\\Shop\\Models\\PaymentItem->deliver()
#8 /var/www/vhosts/hidden.com/httpdocs/plugins/shop/src/Payment/PaymentManager.php(99): Azuriom\\Plugin\\Shop\\Models\\Payment->deliver()
#9 /var/www/vhosts/hidden.com/httpdocs/plugins/shop/src/Controllers/CartController.php(90): Azuriom\\Plugin\\Shop\\Payment\\PaymentManager->buyPackages()
#10 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Azuriom\\Plugin\\Shop\\Controllers\\CartController->payment()
#11 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#12 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#13 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#14 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#15 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#16 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#18 /var/www/vhosts/hidden.com/httpdocs/app/Http/Middleware/LogoutIfSuspended.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Azuriom\\Http\\Middleware\\LogoutIfSuspended->handle()
#20 /var/www/vhosts/hidden.com/httpdocs/app/Http/Middleware/CheckForMaintenanceSettings.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Azuriom\\Http\\Middleware\\CheckForMaintenanceSettings->handle()
#22 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#24 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#26 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#28 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#32 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#33 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#35 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#37 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\\Pipeline\\Pipeline->then()
#39 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#40 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#41 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#42 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#43 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#44 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#46 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#47 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#49 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#50 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#52 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#54 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#56 /var/www/vhosts/hidden.com/httpdocs/plugins/cloudflare/src/Middleware/TrustCloudflare.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Azuriom\\Plugin\\CloudflareSupport\\Middleware\\TrustCloudflare->handle()
#58 /var/www/vhosts/hidden.com/httpdocs/app/Http/Middleware/EnsureInstalled.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Azuriom\\Http\\Middleware\\EnsureInstalled->handle()
#60 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#62 /var/www/vhosts/hidden.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#63 /var/www/vhosts/hidden.com/httpdocs/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#64 /var/www/vhosts/hidden.com/httpdocs/server.php(19): require_once('...')
#65 {main}
"} 
```

### Web server

Apache, Nginx

### Database type

MySQL

### PHP version

8.1

**Comment by MrMicky-FR** [comment]
Seems like your website cannot connect to Stripe services

**Comment by LegoCraftNW** [comment]
But I don't use stripe. I tested it by giving myself coins from the panel without any payment. I will also use paypal as payment system.

**Comment by MrMicky-FR** [comment]
Oops, my bad, your website can’t connect to the Rust server RCON

**Comment by LegoCraftNW** [comment]
> 

![image](https://github.com/Azuriom/Azuriom/assets/21240809/2b66ab6c-d075-48ac-b0c4-45fcd7b8a5ea)
server appears to be accessible

**Comment by LegoCraftNW** [comment]
When I entered the rcon password incorrectly, there was a message in the error logs stating that it could not reach the server, it showed the ip port, but when I entered the rcon password correctly, this error exists.
